services:
  napcat:
    container_name: napcat
    image: mlikiowa/napcat-docker:latest
    environment:
      - NAPCAT_UID=1000
      - NAPCAT_GID=root
    ports:
      - 127.0.0.1:3000:3000
      - 127.0.0.1:3001:3001
      - 6099:6099
    restart: always
    volumes:
      - ./data/qq:/app/.config/QQ
      - ./data/napcat:/app/napcat/config
    networks:
      - bot_network

  astrbot:
    environment:
      - TZ=Asia/Shanghai
    image: soulter/astrbot:latest
    container_name: astrbot
    restart: always
    ports:
      - "6185:6185"
      - "6195:6195"
      - "6199:6199"
    volumes:
      - ./data/AstrBot/data:/AstrBot/data
    networks:
      - bot_network
networks:
  bot_network:
    driver: bridge
